# Generated by Django 5.0.4 on 2026-04-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_projectrole_timelog_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "permissions": [
                    ("edit_project", "Can edit project tasks and columns"),
                    ("manage_project", "Can manage project settings and members"),
                ]
            },
        ),
    ]

