# Generated by Django 5.0.4 on 2026-04-13 14:05

import django.contrib.postgres.indexes
from django.db import migrations


def _add_task_search_gin_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    Task = apps.get_model("projects", "Task")
    index = django.contrib.postgres.indexes.GinIndex(
        fields=["search_vector"],
        name="task_search_gin",
    )
    schema_editor.add_index(Task, index)


def _remove_task_search_gin_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    Task = apps.get_model("projects", "Task")
    index = django.contrib.postgres.indexes.GinIndex(
        fields=["search_vector"],
        name="task_search_gin",
    )
    schema_editor.remove_index(Task, index)


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_project_extra_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["order"]},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_add_task_search_gin_index, _remove_task_search_gin_index),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="task",
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"],
                        name="task_search_gin",
                    ),
                ),
            ],
        ),
    ]

