# Generated by Django 5.0.7 on 2026-04-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_attachment_comment_projectrole_capabilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
