# Generated by Django 5.0.7 on 2026-04-26 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectrole_capabilities_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubPullRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pr_number', models.IntegerField()),
                ('pr_title', models.CharField(max_length=255)),
                ('pr_url', models.URLField()),
                ('repo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed')], default='open', max_length=10)),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='projects.task')),
            ],
            options={
                'unique_together': {('task', 'pr_number', 'repo')},
            },
        ),
    ]
