# Generated by Django 5.0.7 on 2026-04-28 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_task_assignees_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='VcsPullRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket')], max_length=20)),
                ('pr_number', models.IntegerField()),
                ('pr_title', models.CharField(max_length=255)),
                ('pr_url', models.URLField(max_length=500)),
                ('repo', models.CharField(max_length=255)),
                ('status', models.CharField(default='open', max_length=20)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vcs_pull_requests', to='projects.task')),
            ],
            options={
                'unique_together': {('task', 'provider', 'repo', 'pr_number')},
            },
        ),
    ]
