# Generated by Django 5.0.7 on 2026-04-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_vcs_pull_request'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='githubpullrequest',
            unique_together={('task', 'repo', 'pr_number')},
        ),
    ]
