# Generated by Django 5.0.7 on 2026-04-28 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_invoicelineitem_and_more'),
        ('projects', '0014_alter_githubpullrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='billed_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timelogs', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='hourly_rate_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timelog',
            name='is_billable',
            field=models.BooleanField(default=True),
        ),
    ]
