# Generated by Django 5.0.7 on 2026-05-14 11:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_projectdocument_category'),
        ('teams', '0005_team_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('backlog', 'Backlog'), ('discovery', 'Product discovery'), ('wip', 'Dev WIP'), ('review', 'Review'), ('done', 'Done')], default='backlog', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('must_have', 'Must Have'), ('nice_to_have', 'Nice to Have'), ('best_effort', 'Best Effort')], default='must_have', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetroItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('item_type', models.CharField(choices=[('keep', 'Keep'), ('improve', 'Improve'), ('discussion', 'Discussion')], default='discussion', max_length=20)),
                ('is_repeating', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['item_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Retrospective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='resolution_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['team', 'status'], name='projects_pr_team_id_4a0091_idx'),
        ),
        migrations.AddIndex(
            model_name='projectrole',
            index=models.Index(fields=['user'], name='projects_pr_user_id_1ee38c_idx'),
        ),
        migrations.AddField(
            model_name='epic',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_epics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='epic',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_epics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='epic',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='projects.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.epic'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'column', 'order'], name='projects_ta_project_3b4e69_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee'], name='projects_ta_assigne_ef384b_idx'),
        ),
        migrations.AddField(
            model_name='retroitem',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retroitem',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='voted_retro_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retrospective',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retrospective',
            name='sprint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrospective', to='projects.sprint'),
        ),
        migrations.AddField(
            model_name='retrospective',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrospectives', to='teams.team'),
        ),
        migrations.AddField(
            model_name='retroitem',
            name='retrospective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.retrospective'),
        ),
    ]
