# Generated by Django 5.0.4 on 2026-04-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('permission_change', 'Permission Change'), ('approval_change', 'Approval Change'), ('automation_trigger', 'Automation Trigger'), ('notification_rule_change', 'Notification Rule Change'), ('export', 'Export'), ('login', 'Login'), ('logout', 'Logout'), ('invite_sent', 'Invite Sent'), ('invite_accepted', 'Invite Accepted')], max_length=40),
        ),
    ]
