# Generated by Django 5.0.4 on 2026-05-27 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_companymember_role_companyinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=50)),
                ('integration_mode', models.CharField(max_length=20)),
                ('provider', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=50)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('credits_deducted', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('latency_ms', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=15)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('request_summary', models.TextField(blank=True, default='')),
                ('response_preview', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='companies.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Log',
                'verbose_name_plural': 'AI Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAIAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_mode', models.CharField(choices=[('platform_managed', 'Platform-Managed Credits'), ('byok', 'Bring Your Own Key (BYOK)')], default='platform_managed', max_length=30)),
                ('byok_provider', models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini')], max_length=30, null=True)),
                ('byok_api_key_encrypted', models.TextField(blank=True, null=True)),
                ('byok_model_override', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_access', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company AI Access',
                'verbose_name_plural': 'Company AI Accesses',
            },
        ),
        migrations.CreateModel(
            name='CompanyAICredits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_allocated', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credits_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('alert_threshold_percentage', models.IntegerField(default=80)),
                ('alert_triggered', models.BooleanField(default=False)),
                ('last_replenished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_credits', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company AI Credits',
                'verbose_name_plural': 'Company AI Credits',
            },
        ),
    ]
