# Generated by Django 5.0.7 on 2026-06-08 00:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('companies', '0003_companymember_role_companyinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAIBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('feature', models.CharField(max_length=60)),
                ('calls', models.PositiveIntegerField(default=0)),
                ('credits_used', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='ailog',
            name='block_reason',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='ailog',
            name='feedback_rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ailog',
            name='feedback_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ailog',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='ailog',
            name='output_acted_on',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ailog',
            name='output_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ailog',
            name='triggered_by',
            field=models.CharField(choices=[('user_action', 'User action'), ('automation', 'Automation rule'), ('scheduled', 'Scheduled task')], default='user_action', max_length=20),
        ),
        migrations.AlterField(
            model_name='ailog',
            name='feature_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='ailog',
            name='latency_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ailog',
            name='model_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='ailog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked by guardrails')], max_length=15),
        ),
        migrations.AddIndex(
            model_name='ailog',
            index=models.Index(fields=['company', 'feature_name', 'created_at'], name='ailog_co_feat_time_idx'),
        ),
        migrations.AddIndex(
            model_name='ailog',
            index=models.Index(fields=['company', 'status', 'created_at'], name='ailog_co_status_time_idx'),
        ),
        migrations.AddField(
            model_name='dailyaibudget',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_ai_budgets', to='companies.company'),
        ),
        migrations.AddIndex(
            model_name='dailyaibudget',
            index=models.Index(fields=['company', 'date'], name='dailyaibudget_co_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyaibudget',
            unique_together={('company', 'date', 'feature')},
        ),
    ]
