# Generated by Django 5.0.7 on 2026-06-08 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_responsible_ai_governance'),
        ('companies', '0003_companymember_role_companyinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeaturePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_globally_enabled', models.BooleanField(default=True)),
                ('feat_daily_briefing', models.BooleanField(default=True)),
                ('feat_focus_recommend', models.BooleanField(default=True)),
                ('feat_task_description', models.BooleanField(default=True)),
                ('feat_task_summarize', models.BooleanField(default=True)),
                ('feat_auto_label', models.BooleanField(default=True)),
                ('feat_thread_reply_draft', models.BooleanField(default=True)),
                ('feat_sprint_plan', models.BooleanField(default=True)),
                ('feat_workload_balance', models.BooleanField(default=True)),
                ('feat_retrospective', models.BooleanField(default=True)),
                ('feat_project_health', models.BooleanField(default=True)),
                ('feat_blocker_detect', models.BooleanField(default=True)),
                ('feat_escalation_scan', models.BooleanField(default=True)),
                ('feat_weekly_report', models.BooleanField(default=True)),
                ('feat_channel_summary', models.BooleanField(default=True)),
                ('feat_meeting_action_items', models.BooleanField(default=True)),
                ('feat_client_report', models.BooleanField(default=True)),
                ('feat_build_automation', models.BooleanField(default=True)),
                ('feat_portfolio_summary', models.BooleanField(default=True)),
                ('feat_generate_tasks', models.BooleanField(default=True)),
                ('feat_experiment_summary', models.BooleanField(default=True)),
                ('tier_individual', models.CharField(choices=[('fast', 'Fast (cheap, low latency)'), ('standard', 'Standard'), ('premium', 'Premium (complex reasoning)')], default='standard', max_length=20)),
                ('tier_manager', models.CharField(choices=[('fast', 'Fast (cheap, low latency)'), ('standard', 'Standard'), ('premium', 'Premium (complex reasoning)')], default='standard', max_length=20)),
                ('tier_leadership', models.CharField(choices=[('fast', 'Fast (cheap, low latency)'), ('standard', 'Standard'), ('premium', 'Premium (complex reasoning)')], default='premium', max_length=20)),
                ('tier_ds', models.CharField(choices=[('fast', 'Fast (cheap, low latency)'), ('standard', 'Standard'), ('premium', 'Premium (complex reasoning)')], default='standard', max_length=20)),
                ('require_confirm_task_create', models.BooleanField(default=True)),
                ('require_confirm_bulk_label', models.BooleanField(default=True)),
                ('require_confirm_client_report', models.BooleanField(default=True)),
                ('allow_message_content', models.BooleanField(default=True)),
                ('allow_document_content', models.BooleanField(default=False)),
                ('allow_meeting_transcripts', models.BooleanField(default=True)),
                ('log_retention_days', models.PositiveIntegerField(default=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feature_policy', to='companies.company')),
            ],
            options={
                'verbose_name': 'AI Feature Policy',
            },
        ),
    ]
