from django.urls import path
from .views import (
    RegisterView,
    LoginView,
    LogoutView,
    UserMeView,
    ChangePasswordView,
    PasswordResetRequestView,
    PasswordResetConfirmView,
    EmailVerifyRequestView,
    EmailVerifyConfirmView,
    TwoFactorSetupView,
    TwoFactorEnableView,
    TwoFactorDisableView,
    TwoFactorBackupCodesRotateView,
    PushSubscribeView,
    PushVapidKeyView,
    CookieTokenRefreshView,
)
from .oauth_views import (
    BitbucketOAuthCallbackView,
    BitbucketOAuthRedirectView,
    GitHubOAuthCallbackView,
    GitHubOAuthRedirectView,
    GitLabOAuthCallbackView,
    GitLabOAuthRedirectView,
    GoogleCallbackView,
    GoogleRedirectView,
)

urlpatterns = [
    path("register/", RegisterView.as_view(), name="auth_register"),
    path("login/", LoginView.as_view(), name="auth_login"),
    path("logout/", LogoutView.as_view(), name="auth_logout"),
    path("refresh/", CookieTokenRefreshView.as_view(), name="auth_refresh"),
    path("me/", UserMeView.as_view(), name="auth_me"),
    path("change-password/", ChangePasswordView.as_view(), name="auth_change_password"),
    path("password-reset/request/", PasswordResetRequestView.as_view(), name="auth_password_reset_request"),
    path("password-reset/confirm/", PasswordResetConfirmView.as_view(), name="auth_password_reset_confirm"),
    path("email/verify/request/", EmailVerifyRequestView.as_view(), name="auth_email_verify_request"),
    path("email/verify/confirm/", EmailVerifyConfirmView.as_view(), name="auth_email_verify_confirm"),
    path("2fa/setup/", TwoFactorSetupView.as_view(), name="auth_2fa_setup"),
    path("2fa/enable/", TwoFactorEnableView.as_view(), name="auth_2fa_enable"),
    path("2fa/disable/", TwoFactorDisableView.as_view(), name="auth_2fa_disable"),
    path("2fa/backup-codes/rotate/", TwoFactorBackupCodesRotateView.as_view(), name="auth_2fa_backup_rotate"),
    path("push/subscribe/", PushSubscribeView.as_view(), name="push_subscribe"),
    path("push/vapid-key/", PushVapidKeyView.as_view(), name="push_vapid_key"),
    path("oauth/google/redirect/", GoogleRedirectView.as_view(), name="google_redirect"),
    path("oauth/google/callback/", GoogleCallbackView.as_view(), name="google_callback"),
    path("oauth/github/redirect/", GitHubOAuthRedirectView.as_view(), name="github_redirect"),
    path("oauth/github/callback/", GitHubOAuthCallbackView.as_view(), name="github_callback"),
    path("oauth/gitlab/redirect/", GitLabOAuthRedirectView.as_view(), name="gitlab_redirect"),
    path("oauth/gitlab/callback/", GitLabOAuthCallbackView.as_view(), name="gitlab_callback"),
    path("oauth/bitbucket/redirect/", BitbucketOAuthRedirectView.as_view(), name="bitbucket_redirect"),
    path("oauth/bitbucket/callback/", BitbucketOAuthCallbackView.as_view(), name="bitbucket_callback"),
]
