# Generated by Django 5.0.7 on 2026-04-26 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('projects', '0011_githubpullrequest'),
        ('teams', '0004_team_ai_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('github_user', models.CharField(max_length=255)),
                ('repo_owner', models.CharField(blank=True, max_length=255)),
                ('repo_name', models.CharField(blank=True, max_length=255)),
                ('webhook_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_integration', to='projects.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_integrations', to='teams.team')),
            ],
            options={
                'unique_together': {('team', 'project')},
            },
        ),
    ]
