# Generated by Django 5.0.4 on 2026-04-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_gitlab_bitbucket_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcalendaraccount',
            name='provider',
            field=models.CharField(choices=[('google', 'Google Calendar'), ('microsoft', 'Microsoft Outlook')], max_length=20),
        ),
    ]
