# Generated by Django 5.0.7 on 2026-06-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_experiment_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitbucketintegration',
            name='access_token_enc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='externalcalendaraccount',
            name='access_token_enc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='externalcalendaraccount',
            name='refresh_token_enc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='githubintegration',
            name='access_token_enc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gitlabintegration',
            name='access_token_enc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experimentbroadcastconfig',
            name='notify_on_statuses',
            field=models.JSONField(blank=True, default=list, help_text='List of Experiment Status values that trigger a broadcast, e.g. ["Deployed", "Eval Review"]'),
        ),
    ]
