# Generated by Django 5.0.7 on 2026-05-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='permissions_json',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
