# Generated by Django 5.0.4 on 2026-04-17 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_channelmember_notification_settings_scheduledmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_channel',
            field=models.CharField(default='in_app', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_due', 'Task Due'), ('task_overdue', 'Task Overdue'), ('task_watched', 'Task Watched'), ('approval_requested', 'Approval Requested'), ('approval_decided', 'Approval Decided'), ('automation_notice', 'Automation Notice'), ('mentioned_message', 'Mentioned in Message'), ('mentioned_comment', 'Mentioned in Comment'), ('task_moved', 'Task Moved'), ('task_completed', 'Task Completed'), ('invite_accepted', 'Invite Accepted')], max_length=30),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=False)),
                ('due_reminders_enabled', models.BooleanField(default=True)),
                ('overdue_digest_enabled', models.BooleanField(default=True)),
                ('watch_notifications_enabled', models.BooleanField(default=True)),
                ('approval_notifications_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
