# Generated by Django 5.0.7 on 2026-04-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_call_callparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
