# Generated by Django 5.0.4 on 2026-04-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0015_message_seq_and_channel_sequence'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_channel_9ca0ba_idx',
            old_name='msg_chan_seq_idx',
        ),
    ]
