# Generated by Django 5.0.7 on 2026-05-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0016_rename_msg_chan_seq_idx_messaging_m_channel_9ca0ba_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=10),
        ),
    ]
