# Generated by Django 5.0.7 on 2026-05-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0017_call_call_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_due', 'Task Due'), ('task_overdue', 'Task Overdue'), ('task_watched', 'Task Watched'), ('approval_requested', 'Approval Requested'), ('approval_decided', 'Approval Decided'), ('automation_notice', 'Automation Notice'), ('mentioned_message', 'Mentioned in Message'), ('mentioned_comment', 'Mentioned in Comment'), ('task_moved', 'Task Moved'), ('task_completed', 'Task Completed'), ('invite_accepted', 'Invite Accepted'), ('missed_call', 'Missed Call')], max_length=30),
        ),
    ]
